name: Build

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      OS_ARG: ${{ runner.os == 'Windows' && 'win10' || runner.os == 'Linux' && 'linux' || runner.os == 'macOS' && 'osx' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          cache: true
      - run: dotnet restore --locked-mode
      - run: ./createpublishedzip.ps1 -os $OS_ARG
      - uses: actions/upload-artifact@v3
        with:
          path: Release/*.zip
